package com.worldline.mojo.p2repoindex;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.util.Collections;
import java.util.Date;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

import org.apache.maven.model.io.xpp3.MavenXpp3Reader;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;
import org.codehaus.plexus.util.xml.pull.XmlPullParserException;
import org.jdom.Document;
import org.jdom.Element;
import org.jdom.JDOMException;
import org.jdom.input.SAXBuilder;

@Mojo(name = "generate-index", requiresProject = false)
public class P2RepoIndexGeneratorMojo extends AbstractMojo {

	@Parameter(required = false, defaultValue = "${project}")
	private MavenProject mavenProject;

	@Parameter(required = false, property = "repositoryPath")
	private String repositoryPath;

	@Parameter(required = false, property = "documentationUrl")
	private String documentationURL;

	public void execute() throws MojoExecutionException, MojoFailureException {
		// To ensure there is no error.

		getLog().info(String.format("Input parameter [mavenProject=%s]", mavenProject));
		getLog().info(String.format("Input parameter [repositoryPath=%s]", repositoryPath));
		getLog().info(String.format("Input parameter [documentationURL=%s]", documentationURL));

		String repoPath = repositoryPath;

		if (repoPath == null && this.mavenProject != null) {
			File effectiveMavenProject = null;
			try {
				effectiveMavenProject = locateRepositoryProject(this.mavenProject.getFile());
			} catch (Exception e1) {
				e1.printStackTrace();
			}
			if (effectiveMavenProject != null) {
				getLog().debug("Repository Path is null but not Maven Project. Will resolve Repository Path from it");
				String basedirPath = effectiveMavenProject.getPath();
				repoPath = basedirPath.concat(File.separator).concat("target").concat(File.separator)
						.concat("repository");
				getLog().info("Repository Path URL is now " + repoPath);
			}
		}

		String projectURL = documentationURL;
		if (projectURL == null && this.mavenProject != null) {
			projectURL = this.mavenProject.getUrl();
		}

		if (repoPath == null || !new File(repoPath).exists()) {
			getLog().error("Cannot resolve Repository Path at all. Aborts.");
			return;
		}

		File index = new File(repoPath.concat(File.separator).concat("index.html"));
		try {
			index.createNewFile();
		} catch (IOException e) {
			getLog().error("Could not create index file because of " + e.getMessage() + ".", e);
			return;
		}

		// Generate index.html file, to prevent from 404 error when browsing
		// repository.

		RepositoryDescriptor repositoryDescriptor = getRepositoryDescriptor(repoPath);
		Collections.sort(repositoryDescriptor.getFeatureDescriptors());

		try {
			BufferedWriter writer = new BufferedWriter(new FileWriter(index));
			writer.write("<head><link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\"><title>" + repositoryDescriptor.getName() + " Eclipse Update Site</title></head>\n");
			writer.write("<body><div><section><h3>\n");
			writer.write("Welcome on the \"" + repositoryDescriptor.getName() + "\" Eclipse Update Site !\n");
			writer.write("</h3></section><section><p>\n");
			writer.write("<div>As this page is an Eclipse Update Site, it is not intended from browsing.</div>\n");
			writer.write("<div>To use it, please go into your Eclipse instance, and select the <b>Install New Software</b> option with this URL to access the binaries.</div>\n");
			if (projectURL != null && projectURL.length() > 0) {
				writer.write("<div>If you were looking for the documentation of this project, please click <a href=\""
						+ projectURL + "\">here</a> to be redirected.</div>\n");
			}
			writer.write("</p></section><section><p><b>Available features within this update site:</b></p><p>\n");

			writer.write("<table border=\"1\">\n");
			writer.write("<tr><th>Name</th><th>Identifier</th><th>Version</th></tr>\n");
			for (FeatureDescriptor feature : repositoryDescriptor.getFeatureDescriptors()) {
				writer.write(String.format("<tr><td><b>%s</b></td><td>%s</td><td>%s</td></tr>\n", feature.getName(),
						feature.getId(), feature.getVersion()));
			}
			writer.write("</table>\n");

			String builtInformation = "";
			try {
				builtInformation = ", for an Update Site built on "
						+ new Date(Long.parseLong(repositoryDescriptor.getTimestamp()));
			} catch (NumberFormatException nfe) {
			}

			writer.write("</p><p><div><i>(Generated by <a href= \"https://github.com/awltech/eclipse-p2repo-index\">AWLTech p2repo-index-plugin</a> on "
					+ new Date() + builtInformation + ".)</i></div>");
			writer.write("</p></section></div></body>");
			if (getLog().isInfoEnabled())
				getLog().info("Index file generated successfully at " + index.getPath() + ".");
			writer.close();
		} catch (IOException e) {
			getLog().error("Could not write index file because of " + e.getMessage() + ".", e);
			return;
		}
		
		try {
			File f = new File(index.getParentFile().getPath()+File.separator+"style.css");
			if (!f.exists()) {
				f.createNewFile();
				BufferedWriter writer = new BufferedWriter(new FileWriter(f));
				writer.write("body {margin: 5px; text-align: left; font-family: verdana, arial, sans-serif; font-size: 0.8em; color: #333; background-color: #EEE;}\n");
				writer.write("td { font-size: 0.8em;}");
				writer.close();
			}
		} catch (IOException e) {
			getLog().error("Could not write style file because of " + e.getMessage() + ".", e);
			return;
		}

	}

	private MavenProject read(File pomFile) throws Exception {
		if (pomFile == null || !pomFile.exists()) {
			return null;
		}

		FileReader reader = new FileReader(pomFile);
		MavenProject project = new MavenProject(new MavenXpp3Reader().read(reader));
		reader.close();
		return project;
	}

	private File locateRepositoryProject(File mavenProjectFile) throws Exception {
		if (mavenProject == null) {
			return null;
		}
		MavenProject mavenProject = read(mavenProjectFile);
		if (mavenProject != null && "pom".equals(mavenProject.getPackaging())) {
			for (Object o : mavenProject.getModules()) {
				if (o instanceof String) {
					String moduleAsString = (String) o;
					File subPom = new File(mavenProjectFile.getParentFile().getPath() + File.separator + moduleAsString
							+ File.separator + "pom.xml");
					if (subPom.exists()) {
						try {
							FileReader fileReader = new FileReader(subPom);
							MavenProject module = new MavenProject(new MavenXpp3Reader().read(fileReader));
							if ("eclipse-repository".equals(module.getPackaging())) {
								getLog().info("Located repository from parent: " + module.getArtifactId());
								return subPom.getParentFile();
							} else if ("pom".equals(module.getPackaging())) {
								return locateRepositoryProject(subPom);
							}
							fileReader.close();
						} catch (IOException e) {
							e.printStackTrace();
						} catch (XmlPullParserException e) {
							e.printStackTrace();
						}
					}
				}
			}
		}
		return null;
	}

	private RepositoryDescriptor getRepositoryDescriptor(String repoPath) {
		RepositoryDescriptor repositoryDescriptor = new RepositoryDescriptor();
		InputStream contentsFileInputStream = null;
		ZipFile zipFile = null;
		try {

			File xmlFile = new File(repoPath + "/content.xml");
			if (xmlFile != null && xmlFile.exists())
				contentsFileInputStream = new FileInputStream(xmlFile);

			File jarFile = new File(repoPath + "/content.jar");
			if (jarFile != null && jarFile.exists()) {
				zipFile = new ZipFile(jarFile);
				ZipEntry entry = zipFile.getEntry("content.xml");
				if (entry != null) {
					contentsFileInputStream = zipFile.getInputStream(entry);
				}
			}
			if (contentsFileInputStream != null) {
				Document build = new SAXBuilder().build(contentsFileInputStream);
				Element repository = build.getRootElement();

				repositoryDescriptor.setName(repository.getAttributeValue("name"));

				for (Object o : repository.getChild("properties").getChildren("property")) {
					Element e = (Element) o;
					if ("p2.timestamp".equals(e.getAttributeValue("name"))) {
						repositoryDescriptor.setTimestamp(e.getAttributeValue("value"));
					}
				}

				Element units = repository.getChild("units");
				for (Object o : units.getChildren("unit")) {
					Element unit = (Element) o;
					Element unitProperties = unit.getChild("properties");
					Element unitProvides = unit.getChild("provides");

					String featureName = "<UNDEF>";
					String featureVersion = "<UNDEF>";
					String featureId = "<UNDEF>";
					boolean isFeature = false;
					if (unitProperties != null) {
						for (Object o1 : unitProperties.getChildren("property")) {
							Element property = (Element) o1;
							if ("org.eclipse.equinox.p2.name".equals(property.getAttributeValue("name"))) {
								featureName = property.getAttributeValue("value");
							}
						}
					}
					if (unitProvides != null) {
						for (Object o2 : unitProvides.getChildren("provided")) {
							Element provided = (Element) o2;
							if ("org.eclipse.equinox.p2.eclipse.type".equals(provided.getAttributeValue("namespace"))
									&& "feature".equals(provided.getAttributeValue("name"))) {
								isFeature = true;
							}
							if ("org.eclipse.update.feature".equals(provided.getAttributeValue("namespace"))) {
								featureId = provided.getAttributeValue("name");
								featureVersion = provided.getAttributeValue("version");
							}
						}
					}
					if (isFeature) {
						getLog().info("Found feature: " + featureId + ", " + featureName + ", " + featureVersion);
						repositoryDescriptor.getFeatureDescriptors().add(
								new FeatureDescriptor(featureId, featureName, featureVersion));
					}
				}

				return repositoryDescriptor;
			}

		} catch (IOException e) {
			e.printStackTrace();
		} catch (JDOMException e) {
			e.printStackTrace();
		} finally {
			if (contentsFileInputStream != null) {
				try {
					contentsFileInputStream.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
			if (zipFile != null) {
				try {
					zipFile.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}

		return repositoryDescriptor;
	}

}
